### ISSUE TITLE
Points dragged offscreen become "sticky"

### ISSUE THREAD

**Issue by richardjdare** [emnh/glsl-graph#1]
Hi, If you drag a point off the screen (by dragging over the menu on the left, for example) the point becomes stuck. It doesn't spring back like the others. You can still move the point around but it always sticks to where it is put. Am using Chrome 46.0.2490.71 m on Windows 8.1

**Comment by emnh** [comment]
@richardjdare You must be talking about the VivaGraph page ("Supposed to look like" below "Demo"). That's not this project, that one is only provided for reference so you can see what the graph layout should have been rendered like if it had been working correctly. I added a note to make it more clear.
